services:
  xampp:
    platform: linux/x86_64
    build: .
    # image: tomsik68/xampp:8
    ports:
      - "41062:80"
      - "41061:22"
    volumes:
      - ./:/www
      
  
  achecker:
    platform: linux/x86_64
    image: pixelandpen/achecker
    ports:
      - "8000:80"
      - "3307:3306"

    